name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |

            echo " Starting deployment on VM"

            cd ~
            if [ ! -d devops-static-site ]; then
              git clone https://github.com/Rajin-arc/devops-static-site.git
            fi

            cd devops-static-site
            git pull origin main

            echo " Building Docker image on VM"
            docker build -t static-site .

            echo " Stopping old container"
            docker rm -f website || true

            echo " Running new container"
            docker run -d -p 80:80 --name website static-site

            echo " Deployment successful"
