name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo "Connected to VM"

            cd ~
            if [ ! -d devops-static-site ]; then
              git clone https://github.com/Rajin-arc/devops-static-site.git
            fi

            cd devops-static-site
            git pull origin main

            docker build -t static-site .
            docker rm -f website || true
            docker run -d -p 80:80 --name website static-site

            echo "Deployment successful"
